[package]
name = "pynrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pynrs"
crate-type = ["cdylib"]

[dependencies]
pynrs_rust = { path = "../pynrs_rust" }
pyo3 = "0.19.0"
